### ISSUE TITLE
atom-shell causing problems

### ISSUE THREAD

**Issue by kkoopa** [rvagg/nan#226]
https://github.com/brianmcd/contextify/pull/145

I hope this is just some temporary fork and that they'll move to io.js instead of running yet another fork. It will be impossible to support three things each claiming to be Node without any reliable way of telling them apart. Why can't v8 announce which version it is?

**Comment by bnoordhuis** [comment]
> Why can't v8 announce which version it is?

I can try sending a patch.  I remember looking into it one time and not quite being able to figure out how their homegrown release script updated version numbers.

**Comment by kkoopa** [comment]
That would be good. However, Node forkers need to backport that patch too, because having it only in the very latest version of v8 won't do much good in the short time.

**Comment by bnoordhuis** [comment]
You can detect that the version macro is not there, that at least tells you something.  But yes, it won't do a great deal of good in the short term.

**Comment by kkoopa** [comment]
What if every fork could add a define to node-version.h

```c++
#define MY_UNIQUE_DEFINITION 1
```
or use a standard name, but unique value,
```c++
#define NODE_FORK_IDENTIFIER 23
```

**Comment by bnoordhuis** [comment]
It could work but it's not ideal because we're really only interested in the V8 version.  Also, it may be an unreliable indicator when linked against a shared libv8.

**Comment by waTeim** [comment]
Here's some workaround possibilities; tl;dr PREPARSER_H in in 3.25 and 3.26 but not in 3.29, lots of changes in v8 3.14 to 3.25 (V8_ARRAY_BUFFER_VIEW_INTERNAL_FIELD_COUNT for instance)  I have not downloaded iojs yet.  

node 11.14 and 11.13 (v8 3.26.33, 3.25.30)

    bizarro% grep \\#define v8*
    v8-debug.h:#define V8_V8_DEBUG_H_
    v8-platform.h:#define V8_V8_PLATFORM_H_
    v8-preparser.h:#define PREPARSER_H
    v8-preparser.h:#define V8EXPORT __declspec(dllexport)
    v8-preparser.h:#define V8EXPORT __declspec(dllimport)
    v8-preparser.h:#define V8EXPORT
    v8-preparser.h:#define V8EXPORT __attribute__ ((visibility("default")))
    v8-preparser.h:#define V8EXPORT
    v8-profiler.h:#define V8_V8_PROFILER_H_
    v8-testing.h:#define V8_V8_TEST_H_
    v8-util.h:#define V8_UTIL_H_
    v8.h:#define V8_H_
    v8.h:#define TYPE_CHECK(T, S)                                       \
    v8.h:#define V8_ARRAY_BUFFER_INTERNAL_FIELD_COUNT 2
    v8.h:#define V8_ARRAY_BUFFER_VIEW_INTERNAL_FIELD_COUNT 2
    v8config.h:#define V8CONFIG_H_
    v8stdint.h:#define V8STDINT_H_

atom-shell (v8 3.29.88.17)

    bizarro% grep \\#define v8*
    v8-debug.h:#define V8_V8_DEBUG_H_
    v8-platform.h:#define V8_V8_PLATFORM_H_
    v8-profiler.h:#define V8_V8_PROFILER_H_
    v8-testing.h:#define V8_V8_TEST_H_
    v8-util.h:#define V8_UTIL_H_
    v8.h:#define V8_H_
    v8.h:#define TYPE_CHECK(T, S)                                       \
    v8.h:#define V8_ARRAY_BUFFER_INTERNAL_FIELD_COUNT 2
    v8.h:#define V8_ARRAY_BUFFER_VIEW_INTERNAL_FIELD_COUNT 2
    v8config.h:#define V8CONFIG_H_
    v8stdint.h:#define V8STDINT_H_

node 10.35 (v8 3.14.5.9)

    v8-debug.h:#define V8_V8_DEBUG_H_
    v8-debug.h:#define EXPORT __declspec(dllexport)
    v8-debug.h:#define EXPORT __declspec(dllimport)
    v8-debug.h:#define EXPORT
    v8-debug.h:#define EXPORT __attribute__ ((visibility("default")))
    v8-debug.h:#define EXPORT
    v8-platform.h:#define V8_V8_PLATFORM_H_
    v8-preparser.h:#define PREPARSER_H
    v8-preparser.h:#define V8EXPORT __declspec(dllexport)
    v8-preparser.h:#define V8EXPORT __declspec(dllimport)
    v8-preparser.h:#define V8EXPORT
    v8-preparser.h:#define V8EXPORT __attribute__ ((visibility("default")))
    v8-preparser.h:#define V8EXPORT
    v8-profiler.h:#define V8_V8_PROFILER_H_
    v8-profiler.h:#define V8EXPORT __declspec(dllexport)
    v8-profiler.h:#define V8EXPORT __declspec(dllimport)
    v8-profiler.h:#define V8EXPORT
    v8-profiler.h:#define V8EXPORT __attribute__ ((visibility("default")))
    v8-profiler.h:#define V8EXPORT
    v8-testing.h:#define V8_V8_TEST_H_
    v8-testing.h:#define V8EXPORT __declspec(dllexport)
    v8-testing.h:#define V8EXPORT __declspec(dllimport)
    v8-testing.h:#define V8EXPORT
    v8-testing.h:#define V8EXPORT __attribute__ ((visibility("default")))
    v8-testing.h:#define V8EXPORT
    v8-util.h:#define V8_UTIL_H_
    v8.h:#define V8_H_
    v8.h:#define V8EXPORT __declspec(dllexport)
    v8.h:#define V8EXPORT __declspec(dllimport)
    v8.h:#define V8EXPORT
    v8.h:#define V8EXPORT __attribute__ ((visibility("default")))
    v8.h:#define V8EXPORT
    v8.h:#define V8EXPORT
    v8.h:#define TYPE_CHECK(T, S)                                       \
    v8config.h:#define V8CONFIG_H_
    v8stdint.h:#define V8STDINT_H_

**Comment by kkoopa** [comment]
Seems atom-shell is about to upgrade to Chromium 40 and will raise `NODE_MODULE_VERSION` to 100 https://github.com/atom/node/commit/83f1b415e95e4d47e70c1cd064fdf153fc65fc47 and move to io.js. Hopefully the original problem will resolve itself then.

However, being able to actually condition on the v8 version is still highly desirable.

**Comment by waTeim** [comment]
100?  lol.  But there are still incompatible v8 that contextify (among others) have to worry about, though now it's 3 instead of 4 (although I don't know what will happen with node-webkit) if I remember correctly, the list node minor = 10,11,13,17,100 (but 100 == 17), or are you saying that io.js will also change to 100, but no atom might want their freedom and fork io.js too. 

I think I have a solution in mind though, but it will take some cooperation.  Does anyone not use node-gyp these days?

**Comment by kkoopa** [comment]
io.js will stay in range 42 -- 100, atom will be 100+, nw.js will bundle io.js
I imagine atom needs forking mostly to match v8 versions with chrome, which no other project cares about.

This might all still be manageable, but the underlying problem of not being able to reliably identify the version of v8 remains.

**Comment by mathiask88** [comment]
Why do node.js and io.js not offer a V8 version macro of the embedded version? I think the V8 team won't add a macro because there were some tries before and they were rejected. But still a backporting problem :/

**Comment by kkoopa** [comment]
The problem is shared dependencies. Lesser packagers insist on removing bundled dependencies with no regard to patches and modifications.

**Comment by waTeim** [comment]
This can be solved, I feel, so long as the maintainers of node-gyp are agreeable.

**Comment by zcbenz** [comment]
Hi, I'm upgrading atom-shell to [Chrome 40](https://github.com/atom/atom-shell/pull/1002), and I have noticed the problem with compatibility with nan.

In v1.6, nan assumes `NODE_MODULE_VERSION < 42` is Node, otherwise it would be io.js v1.0.0. However atom-shell uses neither, we are currently using https://github.com/atom/node/commit/0d02515d6eb2d57cb602b3924c950936f9745adc which is io.js < v.1.0.0, because atom-shell uses the stable release of Chrome and from https://github.com/atom/node/commit/7f9a6c6213763fbc072e4052e7ce13c6c00648e4 io.js started to use ES6 octal literals that is not available in Chrome 40.

Once after atom-shell starts to use Chrome 41, I can safely set `NODE_MODULE_VERSION` to 42 to make atom-shell compatible with nan, however currently changing `NODE_MODULE_VERSION` to neither 42 or some value smaller won't work.

How about making nan compatible with V8 3.30.33.15 (used by Chrome 40) when `NODE_MODULE_VERSION` is set to 41? So nan still works with Node and io.js v1.0.0, and I can set `NODE_MODULE_VERSION` to 41 in make atom-shell to make it compatible with nan.

And please make sure `NODE_MODULE_VERSION` in io.js bumps when V8 version changes, otherwise we will still have this headache  in future.

**Comment by kkoopa** [comment]
That might work, but the version matrix is already rather complicated. Adding another exception is not the preferred way, but remains a last resort. A related problem is testing, does atom run on travis? How to set it up? Can't know if something breaks if we can't test it.

io.js would not be interested in following chrome versions, will this problem not show up again in the future?

**Comment by bnoordhuis** [comment]
There is still some ongoing discussion on how to set up the release train (iojs/io.js#544) but I believe everyone agrees that io.js will stick to stable V8 releases in the future, meaning it's going to ship the V8 from the latest Chrome release.  We're currently at 4.1 and that won't change until 4.2 goes stable.
