### ISSUE TITLE
Nan breaking node-opencv build

### ISSUE THREAD

**Issue by metalaureate** [rvagg/nan#229]
The latest update to nan is breaking node-opencv

https://github.com/peterbraden/node-opencv/issues/210

I don't know if it is reasonable to report that here, but I'm hoping someone could advise on how to solve the problem.

**Comment by kkoopa** [comment]
It is reasonable to report here, but I believe the error is on opencv's end. The error comes from trying to make a v8::Integer from a long unsigned int. V8 does not support 64-bit integers. You need to downcast to 32 bit. Previously this may have happened implicitly, which was not really proper.

If long is not 64 bit in this case, the problem is likely on our end and needs a small fix.

**Comment by kkoopa** [comment]
Oh, if you just need it installed right now, you can patch package.json in node-opencv and make it use "nan": "~1.4.1" instead of "nan": "^1.3.0", which resolves to 1.5.0 for no good reason. That stupid caret syntax should never have been made the default by npm in the first place.

**Comment by metalaureate** [comment]
Great, thank you.

**Comment by bigthyme** [comment]
thanks @metalaureate  & @kkoopa saved me a lot of time on this.
