### ISSUE TITLE
architecture / threading issues of callback-oriented C++ function wrappers

### ISSUE THREAD

**Issue by jjpepper** [rvagg/nan#232]
Hi,
I'm working on an addon that looks pretty much like [this](https://gist.github.com/dnoiz1/fb7b6583696693b252d5) and I have a question regarding what the C++ side should look like when using all callback-oriented function wrappers.

My addon is basically a whole pile of NAN_METHODs that marshal arguments from v8 to plain C/C++ and then queue a worker function to perform the work, using NanAsyncQueueWorker.

I'm just wondering if this sounds like a normal and fine approach (now that I'm used to it, it seems to be working fine), and I'm also wondering if there are any threading issues or what is the nature of the queue.  I've followed the rule of not using any v8 stuff in the Execute method of my workers, but apart from that are there any important gotchas?  Is there a single worker thread or a thread pool of potentially more than one thread picking jobs off the queue and executing them?

Thanks,
Jesse

**Comment by kkoopa** [comment]
Yes, it sounds perfectly reasonable.

You want to keep the number of transitions from JavaScript to C++ as low as 
possible, since there is a constant overhead for transitioning between the 
two, so if you have a very small amount of work to do, it can often be faster 
to do it all in JavaScript.

Apart from the workers, your C++ code runs in the same thread as v8 and thus 
blocks it from execution, keep this in mind. The workers are built around 
libuv and use a thread pool, default size 4 
http://docs.libuv.org/en/latest/threadpool.html

NanAsyncWorker should cover the most common use cases. If you are doing 
something truly exotic, you may need to directly use libuv instead, but that 
is likely not the case here.

The only other gotcha I can think of right now is that you need to have 
persistent handles of anything you intend to access between async executions, 
as the objects may be garbage collected in the meantime otherwise. This is 
mentioned in the docs for NanAsyncWorker.

**Comment by jjpepper** [comment]
Thanks very much for the helpful feedback :-)
